/* Generated By:JavaCC: Do not edit this line. Trabalho2BConstants.java */
package br.udc.edu.cmp.br;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface Trabalho2BConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int identificador = 5;
  /** RegularExpression Id. */
  int digito = 6;
  /** RegularExpression Id. */
  int letra = 7;
  /** RegularExpression Id. */
  int numero = 8;
  /** RegularExpression Id. */
  int declaracoes = 9;
  /** RegularExpression Id. */
  int lista_identificadores = 10;
  /** RegularExpression Id. */
  int tipo = 11;
  /** RegularExpression Id. */
  int variavel = 12;
  /** RegularExpression Id. */
  int expressao_matematica = 13;
  /** RegularExpression Id. */
  int operando_matematico = 14;
  /** RegularExpression Id. */
  int operador_matematico = 15;
  /** RegularExpression Id. */
  int expressao_logica = 16;
  /** RegularExpression Id. */
  int operando_logico = 17;
  /** RegularExpression Id. */
  int operador_logico = 18;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "\"\\n\"",
    "<identificador>",
    "<digito>",
    "<letra>",
    "<numero>",
    "<declaracoes>",
    "<lista_identificadores>",
    "<tipo>",
    "<variavel>",
    "<expressao_matematica>",
    "<operando_matematico>",
    "<operador_matematico>",
    "<expressao_logica>",
    "<operando_logico>",
    "<operador_logico>",
    "\"{\"",
    "\"}\"",
    "\"=\"",
    "\";\"",
    "\"IF\"",
    "\"THEN\"",
    "\"ELSE\"",
    "\"FOR\"",
    "\"TO\"",
  };

}
